### ISSUE TITLE
Themes, User Stories, Personas pages

### ISSUE THREAD

**Issue by myunusseker** [bounswe/bounswe2016group7#11]
Aydin, 

Can you create Theme, Persona and User Stories pages and write Themes and Persona types that are decided on meeting.

**Comment by TheBoogieman** [comment]
Domain Analysis: https://github.com/bounswe/bounswe2016group7/wiki/Domain-Analysis
User Stories: https://github.com/bounswe/bounswe2016group7/wiki/User-Stories
Personas: https://github.com/bounswe/bounswe2016group7/wiki/Personas
Features/Themes: https://github.com/bounswe/bounswe2016group7/wiki/Features
