### ISSUE TITLE
Adding Use Case Diagrams

### ISSUE THREAD

**Issue by salihegin** [bounswe/bounswe2016group7#19]
Yunus could you please create the use case diagram and add it to the wiki?

**Comment by alpdenizz** [comment]
Use case diagram is ready. Could you please check and resize it?

**Comment by myunusseker** [comment]
Ok i will inform when use case explanations are done

**Comment by alpdenizz** [comment]
I guess there was a task confusion; however, @myunusseker your diagram is more concise.

**Comment by myunusseker** [comment]
Okay then I'm closing the issue, task is done.
