### ISSUE TITLE
Drawing And Searching Class Diagram

### ISSUE THREAD

**Issue by myunusseker** [bounswe/bounswe2016group7#22]
Drawing and searching class diagram is assigned to denizalp

**Comment by alpdenizz** [comment]
https://www.lucidchart.com/invitations/accept/6d0ced42-c43a-45b1-abd9-b7ec3f2383b4
Could you develop this diagram? I could do this much.

**Comment by alpdenizz** [comment]
https://www.lucidchart.com/invitations/accept/e1ebc0e7-c3dd-4eab-8f85-95d45c004ad3
Could you develop this diagram?

**Comment by necil** [comment]
I added new diagram under Class Diagrams wiki page
