### ISSUE TITLE
Login Service Client does not return any user information

### ISSUE THREAD

**Issue by batuhantuna** [bounswe/bounswe2016group7#57]
The client returns a Users class which has only the token. This client should return the user's whole information. Some of them like user_id and username must be put into session by the web application controller. Implementing another client method may be another option but returning the whole user information with login method would be better. This situation blocks the implementation of some pages like profile page.

**Comment by ugurbor** [comment]
I am working on it.

**Comment by ugurbor** [comment]
commited.

414df1c2f50d1655bae187decb462fd3026e4b60
