### ISSUE TITLE
Persona and User Story Creation

### ISSUE THREAD

**Issue by TheBoogieman** [bounswe/bounswe2016group7#9]
Everybody will create:
- at least 5 user stories around the themes in wiki,
  https://github.com/bounswe/bounswe2016group7/wiki/User-Stories
- at least 2 personas around the general categories of personas in wiki, and add them in the pages accordingly.
  https://github.com/bounswe/bounswe2016group7/wiki/Personas

Links to the relevant pages will be added here by me when available.

Deadline is March 6th Monday 17:00.

**Comment by TheBoogieman** [comment]
Links added.

**Comment by myunusseker** [comment]
I wrote 2 personas and 5 User Stories.
